services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: next-saas-rbac
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next-saas-rbac

    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
